name: shellcheck
description: shellcheck action
inputs:
  github_token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
  working_directory:
    description: 'Working Directory'
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: 'Link to Action: https://github.com/suzuki-shunsuke/github-action-shellcheck'
      run: echo "::debug::Link to Action https://github.com/suzuki-shunsuke/github-action-shellcheck"
      shell: bash

    - run: |
        echo "::error ::github_token is required. https://github.com/suzuki-shunsuke/github-action-shellcheck"
        exit 1
      shell: bash
      if: inputs.github_token == ''

    - name: check shellcheck is installed
      run: shellcheck -V
      shell: bash
      working-directory: ${{ inputs.working_directory }}
    - name: check reviewdog is installed
      run: reviewdog -version
      shell: bash
      working-directory: ${{ inputs.working_directory }}

    - name: shellcheck
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.github_token }}
      run: |
        reporter=github-check
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          reporter=github-pr-review
        fi
        tempfile=$(mktemp)
        git ls-files | { grep -E "\.sh$" > "$tempfile" || :; }
        if [ -s "$tempfile" ]; then
          cat "$tempfile" |
            xargs shellcheck --format=checkstyle |
              reviewdog -f=checkstyle \
                -name="shellcheck" \
                -filter-mode=nofilter \
                -reporter="$reporter" \
                -level=warning \
                -fail-on-error=1
        fi
        rm "$tempfile"
