---
name: actionlint
on:
  push:
    branches: [main]
    paths:
    - .github/**
    - aqua/actionlint.yaml
  pull_request:
    branches: [main]
    paths:
    - .github/**
    - aqua/actionlint.yaml
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: aquaproj/aqua-installer@v1.0.0
      with:
        aqua_version: v0.10.2
    - uses: suzuki-shunsuke/github-action-actionlint@v0.1.2
